# Moves
def whitemoves():
    firstpawnfirst = "A3"
    firstpawnsecond = "A4"
    secondpawnfirst = "B3"
    secondpawnsecond = "B4"
    thirdpawnfirst = "C3"
    thirdpawnsecond = "C4"
    fourthpawnfirst = "D3"
    fourthpawnsecond = "D4"
    fifthpawnfirst = "E3"
    fifthpawnsecond = "E4"
    sixthpawnfirst = "F3"
    sixthpawnsecond = "F4"
    seventhpawnfirst = "G3"
    seventhpawnsecond = "G4"
    eighthpawnfirst = "H3"
    eighthpawnsecond = "H4"
